# Permalinks
permalink:           pretty

# Setup
title:               Adam
tagline:             blog
url:                 http://adam-gligor.github.io
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:             Adam Gligor
  url:              https://twitter.com/adamgligor
  email:            gligor.adam@gmail.com


# Custom vars
version:             2.0.0
github:
  repo:             https://github.com/adam-gligor

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

pages_list:
  Blog: '/'
  About: '/about'
  Archive: '/archive'
